kind: "BuildConfig"
apiVersion: "v1"
metadata:
  name: "auth-service-pipeline"
spec:
  strategy:
    jenkinsPipelineStrategy:
      jenkinsfile: |-  
        pipeline {
          agent {
            label 'maven'
          }
          stages {
            stage('Git Checkout') {
              steps {
                git branch: 'master', url: 'http://gogs-cicd.192.168.99.100.nip.io/akkarawu/auth_service.git'
              }
            }
            // Run Maven build, skipping tests
            stage('Build'){
              steps {
                sh "mvn clean install -DskipTests=true -f pom.xml"
              }
            }		
	    // Run Maven unit tests
	    stage('Unit Test'){
	      steps {
	        sh "mvn test -f pom.xml"
	      }
	    }	
          }
        } // pipeline
      type: JenkinsPipeline
