kind: "BuildConfig"
apiVersion: "v1"
metadata:
  name: "auth-service-pipeline"
spec:
  strategy:
    jenkinsPipelineStrategy:
      jenkinsfile: |-  
        pipeline {
          agent {
            label 'maven'
          }
          stages {
            stage('Git Checkout') {
              steps {
                git branch: 'master', url: 'http://gogs-cicd.192.168.99.100.nip.io/akkarawu/auth_service.git'
              }
            }
            // Run Maven build, skipping tests
            stage('Build'){
              steps {
                sh "mvn clean install -DskipTests=true -f pom.xml"
              }
            }
            //sonar
            stage('Code Analysis') {
              steps {
                script {
                  sh "mvn sonar:sonar -Dsonar.host.url=http://sonarqube-cicd.192.168.99.100.nip.io -DskipTests=true"
                }
              }
            }
            //nexus3
            stage('Archive App') {
              steps {
                sh "mvn deploy -DskipTests=true -P nexus3"
              }
            }
          }
        } // pipeline
      type: JenkinsPipeline
